### ISSUE TITLE
Add Startelelogic logo

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/camara-landscape#11]
Dear Admin,

Thank you for your email.

As a company, we are interested in participating in this community because most of our customers are in the telecom sector. By joining, we believe we can contribute significantly and benefit from the shared knowledge and resources. 

We kindly request that our logo be added to the CAMARA website to signify our membership and support. Please find our logo attached to this email for your convenience.

Regards,
Umesh
Mobile +91-9873495558 | Office +91-0120-4333335| [umesh@startelelogic.com](mailto:umesh@startelelogic.com) | 
![Startelelogic-Brandmark-RGB-Colour](https://github.com/camaraproject/camara-landscape/assets/86654280/f9772bd9-b758-4aae-aee1-5775dcb4d746)

**Comment by MarkusKuemmerle** [comment]
![2ih7oQOJgl6UwxC5Lye6JTMqVhS](https://github.com/camaraproject/camara-landscape/assets/86654280/97b5c4fb-80e3-4477-9c46-820b290f4423)

**Comment by wrathwolf** [comment]
Merged with https://github.com/camaraproject/camara-landscape/pull/22
