### ISSUE TITLE
Add BCTI logo

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/camara-landscape#12]
![BCTIv1 g](https://github.com/camaraproject/camara-landscape/assets/86654280/1404b036-9535-44b9-9e93-f878ed11c2a4)

Hello Consulelo,
we’re in progress to improve the CAMARA website. To have the logos presented in the best way we would ask for a .SVG version.
Would you send us your logo again in .SVG format?
BR, Markus

**Comment by wrathwolf** [comment]
BCTI has been added to the Participating Organizations.
