### ISSUE TITLE
Add Italtel logo

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/camara-landscape#13]
Hello Natalia,
we’re in progress to improve the CAMARA website. To have the logos presented in the best way we would ask for a .SVG version.
Would you send us your logo again in .SVG format?
BR, Markus

![logo_italtel-colore (1)](https://github.com/camaraproject/camara-landscape/assets/86654280/40a4a640-f2ed-41af-81af-3b39f8f04a79)

**Comment by wrathwolf** [comment]
The image here is a .jpg

**Comment by MarkusKuemmerle** [comment]
![italtel-spa-vector-logo](https://github.com/camaraproject/camara-landscape/assets/86654280/349f86fe-8178-4900-b86f-5d700a720137)

**Comment by MarkusKuemmerle** [comment]
![logo_italtel-colore (1)](https://github.com/camaraproject/camara-landscape/assets/86654280/e4b4b2d8-18e8-4bf6-a581-35f6da295bb6)

**Comment by wrathwolf** [comment]
https://github.com/camaraproject/camara-landscape/pull/22
