### ISSUE TITLE
Add Optiva logo

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/camara-landscape#14]
Hello Joy,
we’re in progress to improve the CAMARA website. To have the logos presented in the best way we would ask for a .SVG version.
Would you send us your logo again in .SVG format?
BR, Markus

**Comment by MarkusKuemmerle** [comment]
![Optiva_Logo_Black](https://github.com/camaraproject/camara-landscape/assets/86654280/e1990a89-e632-4f98-a143-b92c3f3ec93c)

**Comment by wrathwolf** [comment]
https://github.com/camaraproject/camara-landscape/pull/22
