### ISSUE TITLE
Change logo sequence on website

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/camara-landscape#16]
Change sequence of these logos:
- Cisco is before CK Hutchison
- HKT is behind Hewlett Packard
 
Could Linux Foundation be added between Telus and TruSense?

**Comment by wrathwolf** [comment]
"The Linux Foundation" is not typically added in this fashion to projects for which they are responsible. Is there a reason why we should include them as a "participating organization"?

**Comment by MarkusKuemmerle** [comment]
We've included GSMA too, and both GSMA and LF are hosting organizations for CAMARA. I would treat them the same.

**Comment by wrathwolf** [comment]
Updated and merged with https://github.com/camaraproject/camara-landscape/pull/23
