### ISSUE TITLE
Correct sequence of logos in landscape

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/camara-landscape#24]
Bring logos at landscape in same sequence as on website (website is correct). The following obvious changes are necessary:
![correctsequenceinlandscape](https://github.com/camaraproject/camara-landscape/assets/86654280/ad6ca55e-28e0-4309-8b46-78cb93259c8e)

**Comment by MarkusKuemmerle** [comment]
![Uploading correctsequenceinlandscape.png…]()

**Comment by wrathwolf** [comment]
Resolved with PR #30
