### ISSUE TITLE
Add Eviden to CAMARA project

### ISSUE THREAD

**Issue by vivesml** [camaraproject/camara-landscape#6]
Dear admin,

    I belong to Eviden company and we would like to participate in CAMARA project. We would like to start by having  our logo show up as a participating organization in the CAMARA website. 

    What info do you need me to submit for this?

    Kind regards,

**Comment by eharrison24** [comment]
Hi Herbert,

Thanks for tagging - will handle!

Best,
Evan

**Comment by wrathwolf** [comment]
Hi @vivesml, please provide your organization's logo in .svg format. Additionally, let us know how you would like to participate in the project and if there's anything we can do to assist you with that!

**Comment by vivesml** [comment]
Hi Casey,

      We currently do not have the .svg format. I hope these other formats can be enough.

      I will get back to you on how we would like to participate in the project.

Kind regards / Saludos / Bien à vous / Viele Grüße / Obrigado

Luis Vives
+34 629 850 376

**Comment by wrathwolf** [comment]
Hi @vivesml, unfortunately, the Landscape tool only supports images in .svg format.
There is some tips on converting images in the [README.md](https://github.com/camaraproject/camara-landscape/blob/main/README.md), but I suggest working with your marketing team to produce a high quality version.

**Comment by MarkusKuemmerle** [comment]
![Eviden](https://github.com/camaraproject/camara-landscape/assets/86654280/f66a3d9b-48b0-41ae-9f54-cf3f5c18b589)

**Comment by wrathwolf** [comment]
Merged with https://github.com/camaraproject/camara-landscape/pull/22
